### ISSUE TITLE
Library [emailnator] ain't working

### ISSUE THREAD

**Issue by trueloser777** [hackirby/pynator#1]
```
Traceback (most recent call last):
  File "D:\Projects\Private\Neuer Ordner\main.py", line 133, in <module>
    asyncio.run(main())
  File "C:\Users\homen\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\homen\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\homen\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 664, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "D:\Projects\Private\Neuer Ordner\main.py", line 26, in main
    emailnator = EmailNator()
                 ^^^^^^^^^^^^
  File "D:\Projects\Private\Neuer Ordner\venv\Lib\site-packages\pynator\pynator.py", line 84, in __init__
    super().__init__("https://www.emailnator.com/", "email")
  File "D:\Projects\Private\Neuer Ordner\venv\Lib\site-packages\pynator\pynator.py", line 40, in __init__
    response.raise_for_status()
  File "D:\Projects\Private\Neuer Ordner\venv\Lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://www.emailnator.com/
```

Tried VPN - didn't help. **Site works fine**.

**Comment by hackirby** [comment]
emailnator.com added a Cloudflare challenge, this is why emailnator library is not working anymore.

The resolution involves demonstrating that you've successfully completed the challenge by presenting the cf_clearance cookie.

This library does not include a "Cloudflare Challenge Solver", sorry
